data_dir: "C:\\Users\\user\\Desktop\\COURSES\\AUB\\Spring 2024-2025-739988\\introduction to machine learning\\project 01\\GItHub\\project\\data"
reynolds: [37, 75, 150, 300]
resize: [64, 64]
augment: false
device: "cpu"

drag_normalization: "minmax"      # Options: "minmax", "standard", or "log"

# Baseline Model Configuration
baseline:
  learning_rate: 0.001
  epochs: 50
  batch_size: 64

# CNN Configuration
cnn:
  latent_dim: 64
  learning_rate: 0.0009
  epochs: 100
  batch_size: 300

# LSTM Configuration (with Physics-Informed Loss)
lstm:
  input_size: 64
  hidden_size: 32
  num_layers: 1
  output_size: 1
  epochs: 50
  learning_rate: 0.001
  physics_loss_weight: 0.01
