version: "3.8"

x-common-env: &common-env
  environment:
    - PYTHONUNBUFFERED=1
    - ENVIRONMENT=production
    - LOGGING_LEVEL=INFO
    - TZ=UTC

x-common-volumes: &common-volumes
  volumes:
    - ./:/app
    - ./logs:/app/logs
    - ./data:/app/data
    - ./config:/app/config
    - type: volume
      source: model-cache
      target: /app/models

x-common-healthcheck: &common-healthcheck
  healthcheck:
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
      cache_from:
        - python:3.12-slim-bullseye
    command: >
      sh -c "streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=true --server.runOnSave=false --server.fileWatcherType none"
    ports:
      - "8501:8501"
    <<: [*common-env, *common-volumes, *common-healthcheck]
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
      cache_from:
        - python:3.12-slim-bullseye
    command: >
      sh -c "gunicorn --workers=4 --threads=2 --bind=0.0.0.0:5000 --access-logfile=/app/logs/gunicorn_access.log --error-logfile=/app/logs/gunicorn_error.log --capture-output --log-level=info api_server:app"
    ports:
      - "5000:5000"
    <<: [*common-env, *common-volumes, *common-healthcheck]
    restart: unless-stopped

volumes:
  model-cache:
  logs:
  data:
